let caps = []
let result_image = null
let HEIGHT = 800
let SHOW_STATE = 0
let w, h

let cap_colors = []


function preload() {
	result_image = new ResultImage(image_path)

	caps = [
		new Cap("assets/cap/Grim Ambre.jpg", 131),
		new Cap("assets/cap/Goudale.jpg", 92),
		new Cap("assets/cap/Legere.jpg", 54),
		new Cap("assets/cap/Paulaner.jpg", 60),
		new Cap("assets/cap/Corona.jpg", 55),
		new Cap("assets/cap/Affligen Blue.jpg", 77), 
		new Cap("assets/cap/Jenlain.jpg", 73),
		new Cap("assets/cap/Pietra.jpg", 53),
		new Cap("assets/cap/1664.jpg", 45),
		new Cap("assets/cap/Cross.jpg", 35),
		new Cap("assets/cap/White.jpg", 4),
		// new Cap("assets/cap/Hoegarden.jpg", 6), 
		new Cap("assets/cap/1664 Blanc.jpg", 5), 
		new Cap("assets/cap/Eguzki.jpg", 10), 
		new Cap("assets/cap/Compass.jpg", 5), 
		new Cap("assets/cap/Schlenkerla.jpg", 3), 
		new Cap("assets/cap/Asahi.jpg", 3), 
		new Cap("assets/cap/Brewdog Blue.jpg", 4), 
		// new Cap("assets/cap/Ratz Gold.jpg", 12), 
		new Cap("assets/cap/Dunkel.jpg", 6), 
		new Cap("assets/cap/Panache.jpg", 4), 
		new Cap("assets/cap/Vietman.jpg", 7), 
		new Cap("assets/cap/h.jpg", 6), 
		new Cap("assets/cap/Agneau.jpg", 3), 
		new Cap("assets/cap/Francaise.jpg", 2), 
		new Cap("assets/cap/Ra Mi.jpg", 2), 
		new Cap("assets/cap/G Green.jpg", 3), 
		// new Cap("assets/cap/G Yellow.jpg", 4), 
		// new Cap("assets/cap/Red Flower.jpg", 4), 
		new Cap("assets/cap/13.jpg", 2), 
		new Cap("assets/cap/Leffe Miel.jpg", 10), 
		new Cap("assets/cap/Affligen Bord.jpg", 37), 
		new Cap("assets/cap/Heineken 0.jpg", 50), 
		new Cap("assets/cap/Castelain Gold.jpg", 55), 
		new Cap("assets/cap/Castelain White.jpg", 16), 
		new Cap("assets/cap/Brooklyn.jpg", 61), 
		new Cap("assets/cap/Recyclable.jpg", 26), 
		new Cap("assets/cap/Chouffe.jpg", 48), 
		new Cap("assets/cap/Lagunitas.jpg", 47), 
		new Cap("assets/cap/Erdinger Ble.jpg", 19), 
		new Cap("assets/cap/Grim Blonde.jpg", 33),
		new Cap("assets/cap/Wolf.jpg", 1),
		new Cap("assets/cap/Grim Blanche.jpg", 1),
		new Cap("assets/cap/Licorne.jpg", 2),
		new Cap("assets/cap/Green Castle.jpg", 1),
		new Cap("assets/cap/Lbf.jpg", 1),
		new Cap("assets/cap/Vedett.jpg", 1),
		new Cap("assets/cap/Krombacher.jpg", 1),
		new Cap("assets/cap/M.jpg", 2),
		// new Cap("assets/cap/b.jpg", 1),
		new Cap("assets/cap/Bourbon.jpg", 2),
		// new Cap("assets/cap/Kro.jpg", 1),
		// new Cap("assets/cap/Paulaner White.jpg", 2),
		new Cap("assets/cap/Roma.jpg", 1),
		new Cap("assets/cap/Sunset.jpg", 6),
		// new Cap("assets/cap/British.jpg", 1),
		new Cap("assets/cap/Lagunitas Green.jpg", 1),
		new Cap("assets/cap/Affligen.jpg", 5),
		// new Cap("assets/cap/Woman Green.jpg", 1),
		// new Cap("assets/cap/Gold Flash.jpg", 10),
		new Cap("assets/cap/75.jpg", 1),
		// new Cap("assets/cap/Mort Subite.jpg", 1),
		// new Cap("assets/cap/Jonte.jpg", 1),
		// new Cap("assets/cap/Piou.jpg", 1),
		new Cap("assets/cap/Guiness Black.jpg", 1),
		new Cap("assets/cap/Yellow.jpg", 5),
		new Cap("assets/cap/KissWing Yellow.jpg", 1),
		// new Cap("assets/cap/Orange.jpg", 6),
		new Cap("assets/cap/Plzen.jpg", 6),
		// new Cap("assets/cap/Coq.jpg", 1),
		// new Cap("assets/cap/Gold Soft.jpg", 11),
		new Cap("assets/cap/Heineken.jpg", 3),
		new Cap("assets/cap/Green.jpg", 1),
		new Cap("assets/cap/Red.jpg", 1),
		new Cap("assets/cap/B12.jpg", 12),
		new Cap("assets/cap/Leffe Ambre.jpg", 8),
		new Cap("assets/cap/Leffe.jpg", 27),
		new Cap("assets/cap/Dremmwel.jpg", 11),
		// new Cap("assets/cap/Castle.jpg", 1),
		new Cap("assets/cap/Doigt.jpg", 10),
		new Cap("assets/cap/Black.jpg", 12),
		new Cap("assets/cap/Jack Daniel.jpg", 5),
		new Cap("assets/cap/Silver.jpg", 4),
		new Cap("assets/cap/Brewdog Black.jpg", 21),
		new Cap("assets/cap/Leffe Brown.jpg", 19),
		new Cap("assets/cap/Devil.jpg", 21),
		new Cap("assets/cap/Ratz.jpg", 3),
		new Cap("assets/cap/Grim Verte.jpg", 3),
		new Cap("assets/cap/Chimay Gold.jpg", 4),
		new Cap("assets/cap/Blue Dutch.jpg", 1),
		new Cap("assets/cap/Corsaire.jpg", 1),
		// new Cap("assets/cap/Chti.jpg", 6),
		new Cap("assets/cap/Moustache.jpg", 11),
		new Cap("assets/cap/5.jpg", 16),
		new Cap("assets/cap/Heineken.jpg", 3),
		new Cap("assets/cap/Kwak Red.jpg", 1),
		new Cap("assets/cap/Occitan.jpg", 3),
		new Cap("assets/cap/Edelweiss.jpg", 2),
		new Cap("assets/cap/Gold.jpg", 10),
		// new Cap("assets/cap/Duvel.jpg", 2),
		new Cap("assets/cap/Super Bock.jpg", 7),
		new Cap("assets/cap/Couronne.jpg", 18),
		// new Cap("assets/cap/Seine.jpg", 22),
	]


}

function get_cap_by_path(path) {
	return caps.find(cap => cap.path == path);
}